# Generated by Django 5.0.3 on 2024-04-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_product_size_delete_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
