# Generated by Django 5.0.3 on 2024-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.URLField(null=True),
        ),
    ]
